"""
Obstacle Model - Represents dynamic obstacles/threats on routes.
Generated by AI (simulating Janus 7B) and countered by management heuristics.
"""

from sqlalchemy import String, Integer, Float, Boolean, Column, DateTime, JSON, ForeignKey
from sqlalchemy.orm import relationship
from datetime import datetime
from app.core.database import Base


class Obstacle(Base):
    """
    Dynamic obstacles that appear on routes and affect convoy movement.
    These are generated by the AI obstacle generator to test the system's resilience.
    """
    __tablename__ = "obstacles"

    id = Column(Integer, primary_key=True, index=True)
    
    # Obstacle classification
    obstacle_type = Column(String, index=True, doc="""
        LANDSLIDE, ROADBLOCK, WEATHER_SEVERE, WEATHER_MODERATE, 
        SECURITY_THREAT, IED_SUSPECTED, AMBUSH_RISK, BRIDGE_DAMAGE,
        FLOODING, SNOWFALL, FOG, BREAKDOWN_ZONE, TCP_CLOSURE,
        ACCIDENT, ROCKFALL, AVALANCHE
    """)
    severity = Column(String, default="MEDIUM", doc="LOW, MEDIUM, HIGH, CRITICAL")
    
    # Location
    latitude = Column(Float, nullable=False)
    longitude = Column(Float, nullable=False)
    radius_km = Column(Float, default=0.5, doc="Affected radius in km")
    route_id = Column(Integer, ForeignKey("routes.id"), nullable=True)
    route_km_marker = Column(Float, nullable=True, doc="Km marker on the route")
    
    # Timing
    detected_at = Column(DateTime, default=datetime.utcnow)
    estimated_duration_hours = Column(Float, default=2.0)
    expires_at = Column(DateTime, nullable=True)
    
    # Status
    status = Column(String, default="ACTIVE", doc="ACTIVE, MITIGATED, EXPIRED, CLEARED")
    is_active = Column(Boolean, default=True)
    
    # Impact assessment
    impact_score = Column(Float, default=50.0, doc="0-100 impact severity")
    affected_convoys = Column(JSON, default=list, doc="List of convoy IDs affected")
    blocks_route = Column(Boolean, default=False, doc="Does this completely block the route?")
    speed_reduction_factor = Column(Float, default=1.0, doc="0.0 = blocked, 1.0 = no impact")
    
    # AI Generation metadata
    generated_by = Column(String, default="JANUS_SIM", doc="AI model that generated this")
    generation_context = Column(JSON, nullable=True, doc="Context used for generation")
    
    # Countermeasure tracking
    countermeasure_id = Column(Integer, ForeignKey("countermeasures.id"), nullable=True)
    is_countered = Column(Boolean, default=False)
    countered_at = Column(DateTime, nullable=True)
    
    # Description
    title = Column(String, nullable=True)
    description = Column(String, nullable=True)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class Countermeasure(Base):
    """
    AI-generated responses to obstacles.
    These demonstrate the system's ability to adapt and overcome challenges.
    """
    __tablename__ = "countermeasures"

    id = Column(Integer, primary_key=True, index=True)
    
    # Target
    obstacle_id = Column(Integer, ForeignKey("obstacles.id"), nullable=False)
    
    # Countermeasure type
    action_type = Column(String, doc="""
        ROUTE_DIVERSION, CONVOY_HALT, CONVOY_REROUTE, SPEED_ADJUSTMENT,
        ASSET_REASSIGNMENT, PRIORITY_ELEVATION, WAIT_AND_MONITOR,
        EMERGENCY_PROTOCOL, RESOURCE_DISPATCH, CONVOY_MERGE,
        SCHEDULE_DELAY, ALTERNATE_TCP, ESCORT_REQUEST
    """)
    
    # Decision details
    decision_algorithm = Column(String, doc="Algorithm/heuristic used")
    confidence_score = Column(Float, default=0.8, doc="AI confidence in this decision")
    decision_factors = Column(JSON, doc="Factors considered in decision")
    
    # Execution
    status = Column(String, default="PROPOSED", doc="PROPOSED, APPROVED, EXECUTING, COMPLETED, FAILED")
    executed_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)
    
    # Impact
    affected_convoys = Column(JSON, default=list)
    affected_assets = Column(JSON, default=list)
    new_route_id = Column(Integer, ForeignKey("routes.id"), nullable=True)
    eta_impact_minutes = Column(Integer, default=0)
    
    # Details
    title = Column(String, nullable=True)
    description = Column(String, nullable=True)
    execution_steps = Column(JSON, default=list)
    
    # Results
    success = Column(Boolean, nullable=True)
    outcome_notes = Column(String, nullable=True)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    obstacles = relationship("Obstacle", foreign_keys=[obstacle_id], backref="countermeasures_applied")


class SimulationEvent(Base):
    """
    Log of all simulation events for analysis and visualization.
    """
    __tablename__ = "simulation_events"

    id = Column(Integer, primary_key=True, index=True)
    
    event_type = Column(String, doc="OBSTACLE_CREATED, OBSTACLE_DETECTED, COUNTERMEASURE_TRIGGERED, COUNTERMEASURE_SUCCESS, CONVOY_AFFECTED, ROUTE_CHANGED")
    
    # References
    obstacle_id = Column(Integer, ForeignKey("obstacles.id"), nullable=True)
    countermeasure_id = Column(Integer, ForeignKey("countermeasures.id"), nullable=True)
    convoy_id = Column(Integer, ForeignKey("convoys.id"), nullable=True)
    route_id = Column(Integer, ForeignKey("routes.id"), nullable=True)
    
    # Event data
    event_data = Column(JSON, doc="Full event payload")
    severity = Column(String, default="INFO", doc="INFO, WARNING, ALERT, CRITICAL")
    
    # Timestamps
    timestamp = Column(DateTime, default=datetime.utcnow)
    
    # For frontend consumption
    is_read = Column(Boolean, default=False)
    is_displayed = Column(Boolean, default=False)
